### ISSUE TITLE
Javascript Error in Linux

### ISSUE THREAD

**Issue by Brin-o** [jasonlong/mater#126]
Hi, running mater on Pop OS 20.04, fresh install, I get this error in the terminal.

Are there any dependencies that I should have for this to work?

````
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-debug'
Require stack:
- /home/brin/Downloads/Mater-linux-x64/resources/app/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/brin/Downloads/Mater-linux-x64/resources/app/main.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
`
```

**Comment by jasonlong** [comment]
Hi @Brin-o. Would you mind trying this version:

https://github.com/jasonlong/mater/releases/tag/v1.0.7-canary.1

I built this earlier today while trying to debug a similar problem with the new version of macOS. It didn't entirely fix that bug, but I'm curious if it helps here.

**Comment by Brin-o** [comment]
Hi! It does boot now, however I'd argue that there are still some issues with it.
1) The icon does not respect the panel colour resulting in poor contrast (black icon on dark panel)
2) To open the app there is a required step to click an empty dropdown menu button. I understand this might be a app indicator limitation here since the app is not a gnome extension, however adding text to it ("Open Mater") would make the drop down a bit more logical.
![mater_linux](https://user-images.githubusercontent.com/49071768/99507640-eedf5380-2983-11eb-9b5f-8f9719d31fc0.gif)

**Comment by jasonlong** [comment]
Thanks for the report, @Brin-o. I was hoping the newer version of menubar would fix this, but no such luck. Unfortunately, I don't have a way to test the app on Linux and I just have to release it blindly. I'll put a `help-wanted` label on here to see if anyone else is able to disagnose.
